chore: 깃 액션-Failed to add server host key to known_hosts

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,7 +40,13 @@ jobs:
       - name: Add server host key to known_hosts
         run: |
           mkdir -p ~/.ssh || { echo "Failed to create .ssh directory"; exit 1; }
-          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || { echo "Failed to add server host key to known_hosts"; exit 1; }
+          HOST_KEY=$(ssh-keygen -H -F ${{ secrets.SERVER_HOST }} 2>/dev/null)
+          if [ -z "$HOST_KEY" ]; then
+            ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || { echo "Failed to add server host key to known_hosts"; exit 1; }
+            echo "Server host key added successfully."
+          else
+            echo "Server host key already exists in known_hosts."
+          fi
 
       - name: Copy install.sh to server
         run: scp scripts/install.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/install.sh
